steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'my-cloud-function'
      - '--runtime'
      - 'python39'  
      - '--trigger-http'
      - '--entry-point'
      - 'wikipedia_etl'  
      - '--source=Deepl_reproduction/ETL' 
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
