steps:
  # Étape 1 : Installation des dépendances
  - name: 'python:3.9'  # Remplacez par la version de Python appropriée
    entrypoint: 'pip3'
    args: ['install', '-r', 'requirements.txt']  # Assurez-vous d'avoir un fichier requirements.txt à la racine de votre repository avec les dépendances nécessaires.

  # Étape 2 : Exécution de la Cloud Function
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'python39'
      - '--runtime'
      - 'python39'
      - '--trigger-http'
      - '--allow-unauthenticated'
      - '--entry-point'
      - 'wikipedia_etl'
      - '--source=Deepl_reproduction/ETL'
      # Remplacez NOM_DU_PROJET par le nom de votre projet GCP
      # Remplacez DEPOT_DU_CODE_SOURCE par le nom du dépôt du code source (ou laissez-le vide si vous utilisez le dépôt par défaut)

timeout: '1600s'  # Augmentez le timeout si nécessaire, en fonction de la taille de votre projet et du temps d'exécution.
