steps:
# Étape 1 : Cloner le dépôt GitHub contenant la Cloud Function
- name: "gcr.io/cloud-builders/git"
  args: ["clone", "https://github.com/HippolyteGuigon/Deepl_reproduction.git", "workspace"]
  dir: "/workspace"

# Étape 2 : Installer les dépendances Python dans le répertoire du projet en utilisant Python 3.10
- name: "python:3.10"
  entrypoint: "/bin/sh"
  args:
    - "-c"
    - |
      python -m pip install -r /workspace/requirements.txt --target /workspace

  dir: "/workspace"

# Étape 3 : Installer les dépendances Python dans le répertoire du projet en utilisant Python 3.10
- name: "python:3.10"
  entrypoint: "/bin/sh"
  args:
    - "-c"
    - |
      python /workspace/setup.py install 

  dir: "/workspace/Deepl_reproduction/ETL"

# Étape 4 : Déployer la Cloud Function à partir du répertoire cloné
- name: "gcr.io/cloud-builders/gcloud"
  args: ["functions", "deploy", "Deepl_reproduction",
         "--runtime", "python310",
         "--trigger-http",
         "--entry-point", "wikipedia_etl_pipeline",
         "--source", "/workspace/Deepl_reproduction/ETL"]
  dir: "/workspace/Deepl_reproduction/ETL"
