steps:
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
          export PYTHONPATH="${PYTHONPATH}:/workspace/Deepl_reproduction"
          python3 main.py
  - name: 'python:3.9'  # Remplacez par la version de Python appropriée
    entrypoint: 'pip3'
    args: ['install', '-r', 'requirements.txt']

  - name: 'python:3.9'  # Remplacez par la version de Python appropriée
    entrypoint: 'python3'
    args: ['setup.py', 'install']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'python39', '--runtime', 'python39', '--trigger-http', '--allow-unauthenticated', '--entry-point', 'wikipedia_etl_pipeline', '--source=Deepl_reproduction/ETL']
