steps:
  # Étape 1 : Cloner le repository GitHub
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/HippolyteGuigon/Deepl_reproduction.git', 'temporary_repo/']
    dir: '/workspace'

  # Étape 2 : Installation des dépendances
  - name: 'python:3.9'  # Remplacez par la version de Python appropriée
    entrypoint: 'pip3'
    args: ['install', '-r', 'requirements.txt']
    dir: '/workspace/temporary_repo/'
  
  - name: 'python:3.9'  # Remplacez par la version de Python appropriée
    entrypoint: 'python3'
    args: ['setup.py', 'install']
    dir: '/workspace/temporary_repo/'

  # Étape 3 : Exécution de la Cloud Function
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'gcloud'
    args: ['functions', 'deploy', 'python39', '--runtime', 'python39', '--trigger-http', '--allow-unauthenticated', '--entry-point', 'wikipedia_etl_pipeline', '--source', 'Deepl_reproduction/ETL']
    dir: '/workspace'

timeout: '3200s'  # Augmentez le timeout si nécessaire, en fonction de la taille de votre projet et du temps d'exécution.
