steps:
  # Étape 1 : Installation des dépendances
  - name: 'python:3.9'  # Remplacez par la version de Python appropriée
    entrypoint: 'pip3'
    args: ['install', '-r', 'requirements.txt']  # Assurez-vous d'avoir un fichier requirements.txt à la racine de votre repository avec les dépendances nécessaires.

  # Étape 2 : Exécution de la Cloud Function
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'python39', '--runtime', 'python39', '--trigger-http', '--allow-unauthenticated', '--entry-point', 'wikipedia_etl', '--source', '.']

timeout: '1600s'  # Augmentez le timeout si nécessaire, en fonction de la taille de votre projet et du temps d'exécution.
