steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'my-cloud-function'
      - '--runtime'
      - 'python39'  
      - '--trigger-http'
      - '--entry-point'
      - 'wikipedia_etl'  # Remplacez par le nom de la fonction à exécuter
      - '--source'
      - 'Deepl_reproduction/ETL/main.py'  # Remplacez par le chemin relatif vers le répertoire contenant votre fonction
      - '--region'
      - 'us-central1'  # Remplacez par la région de votre choix
      - '--allow-unauthenticated'  # Cette option permet aux utilisateurs non authentifiés d'appeler votre fonction
