steps:
# Étape 1 : Cloner le dépôt GitHub contenant la Cloud Function
- name: "gcr.io/cloud-builders/git"
  args: ["clone", "https://github.com/HippolyteGuigon/Deepl_reproduction.git", "workspace"]
  dir: "/workspace"

# Étape 2 : Construire l'image Docker personnalisée pour installer les dépendances
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "python310-deps", "-f", "Dockerfile", "."]
  dir: "/workspace"

# Étape 3 : Déployer la Cloud Function à partir du répertoire cloné
- name: "gcr.io/cloud-builders/gcloud"
  args: ["functions", "deploy", "Deepl_reproduction",
         "--runtime", "python310",
         "--trigger-http",
         "--entry-point", "wikipedia_etl_pipeline",
         "--source", "/workspace/Deepl_reproduction/ETL"]
  dir: "/workspace/Deepl_reproduction"
