steps:
# Étape 1 : Cloner le dépôt GitHub contenant la Cloud Function
- name: "gcr.io/cloud-builders/git"
  args: ["clone", "https://github.com/HippolyteGuigon/Deepl_reproduction.git", "workspace"]
  dir: "/workspace"

# Étape 2 : Installer les dépendances Python dans le répertoire du projet en utilisant Python 3.9
- name: "gcr.io/cloud-builders/python:3.9"
  args: ["-m", "pip", "install", "-r", "/workspace/requirements.txt", "--target", "/workspace"]
  dir: "/workspace"

# Étape 3 : Ajouter le chemin du répertoire racine du projet au sys.path
- name: "gcr.io/cloud-builders/gcloud"
  args: ["functions", "deploy", "Deepl_reproduction",
         "--runtime", "python310",
         "--trigger-http",
         "--entry-point", "wikipedia_etl_pipeline",
         "--source", "/workspace/Deepl_reproduction/ETL"]
  dir: "/workspace"
  env:
    - "PYTHONPATH=/workspace:/workspace/Deepl_reproduction"
