# Utilisez une image Python de base
FROM python:latest

EXPOSE 8501
# Définissez le répertoire de travail à /app
WORKDIR /app

# Copiez le fichier Python dans le conteneur
COPY . /app/

# Installez les dépendances Python si nécessaire (requirements.txt)
RUN pip install -r requirements.txt

# Exécutez le fichier Python lorsque le conteneur est démarré
CMD ["streamlit", "run", "app.py"]
