FROM ubuntu:bionic

RUN apt-get update && \
    apt-get install -y curl gnupg && \
    echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && \
    apt-get update -y && \
    apt-get install google-cloud-sdk -y

WORKDIR app/

RUN mkdir model_bucket/

RUN gsutil cp gs://english_deepl_bucket/deepl_english_model_loss_2_881014585494995.pth.tar model_bucket/ &&\
    gsutil cp gs://english_deepl_bucket/bpe.model model_bucket/
