# Utilisez l'image python officielle en tant qu'image de base
FROM python:3.9

# Définir le répertoire de travail
WORKDIR /app

# Copier le contenu du répertoire actuel dans le conteneur à /app
COPY Deepl_reproduction/ETL /app

# Installez les dépendances requises spécifiées dans le fichier requirements.txt
COPY Deepl_reproduction/ETL/requirements.txt /app
RUN pip install -r requirements.txt

# Exécutez votre script ou votre fonction ici (par exemple, en utilisant CMD ou ENTRYPOINT)
# Assurez-vous que votre main.py a une fonction nommée 'wikipedia_etl' comme point d'entrée
CMD ["python", "main.py", "wikipedia_etl"]
