version: '3'

services:
  data-fetcher:
    build:
      context: .
      dockerfile: Dockerfile-model-loading  # Le chemin vers le Dockerfile du service data-fetcher
    volumes:
      - ./data:/app/model_bucket
    command: sh -c "sleep 10 && gsutil cp gs://english_deepl_bucket/deepl_english_model_loss_2_881014585494995.pth.tar model_bucket/ && gsutil cp gs://english_deepl_bucket/bpe_english.model model_bucket/"
    networks:
      - mynetwork

  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile-streamlit  # Le chemin vers le Dockerfile du service streamlit-app
    ports:
      - "8501:8501"
    depends_on:
      - data-fetcher
    networks:
      - mynetwork

networks:
  mynetwork:
