# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python3 -m pip3 install --upgrade pip
        python3 setup.py install
        pip install flake8 pytest
        pip3 install Cython
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
        pip3 install --upgrade mysql-connector-python
        pip3 install google-cloud-bigquery
        pip3 install wheel
        pip3 install pymysql
        pip3 install mysqlclient
        pip3 install PyMySQL
        pip3 install cryptography
      continue-on-error: true
    - name: Test with pytest
      run: |
        pytest
